function postSeisData = bsGetPostSeisData(GInvParam, inIds, crossIds, startTime, sampNum)

    if isfield(GInvParam, 'postSeisData') && exist(GInvParam.postSeisData.fileName, 'file')
        [postSeisData, ~] = bsReadTracesByIds(...
            GInvParam.postSeisData.fileName, ...
            GInvParam.postSeisData.segyInfo, ...
            inIds, ...
            crossIds, ...
            startTime, ...
            sampNum, ...
            GInvParam.dt);
    elseif ~strcmpi(GInvParam.preSeisData.mode, 'angle_separate_files')
        postSeisData = bsStackPreSeisData(...
            GInvParam.preSeisData.fileName, ...
            GInvParam.preSeisData.segyInfo, ...
            inIds, ...
            crossIds, ...
            startTime, ...
            sampNum, ...
            GInvParam.dt);
    else
        separates = GInvParam.preSeisData.separates;
        traceNum = length(inIds);
        
        postSeisData = zeros(sampNum, traceNum);
        
        for i = 1 : traceNum
            angleSeisData = bsReadMultiSegyFiles(separates, inIds(i), crossIds(i), ...
                startTime(i), sampNum, GInvParam.dt);
            
            postSeisData(:, i) = sum(angleSeisData, 2) / length(separates);
        end
        
    end
    
end