function postSeisData = bsGetPostSeisData(GInvParam, inIds, crossIds, startTime, sampNum)
    if isfield(GInvParam, 'postSeisData') && isfile(GInvParam.postSeisData.segyFileName)
        [postSeisData, ~] = bsReadTracesByIds(...
            GInvParam.postSeisData.segyFileName, ...
            GInvParam.postSeisData.segyInfo, ...
            inIds, ...
            crossIds, ...
            startTime, ...
            sampNum, ...
            GInvParam.dt);
    else
        postSeisData = bsStackPreSeisData(...
            GInvParam.preSeisData.segyFileName, ...
            GInvParam.preSeisData.segyInfo, ...
            inIds, ...
            crossIds, ...
            startTime, ...
            sampNum, ...
            GInvParam.dt);
    end
    
end