function [paths] = bsGetInvResultsPathsByName(basePath, methodName, fileName)
    paths = { ...
        [sprintf('%s/%s/sgy_results/%s.sgy', basePath, methodName, sprintf(fileName, 'vp'))];...
        [sprintf('%s/%s/sgy_results/%s.sgy', basePath, methodName, sprintf(fileName, 'vs'))];...
        [sprintf('%s/%s/sgy_results/%s.sgy', basePath, methodName, sprintf(fileName, 'rho'))]};
end