function [wellData, timeData] = bsGetWellData(GInvParam, wellLogs, wellHorizonTimes, dataIndex, filtCoef)

    sampNum = GInvParam.upNum + GInvParam.downNum;
    wellNum = length(wellLogs);
    
    wellData = zeros(sampNum, wellNum);
    timeData = zeros(sampNum, wellNum);
    
    for i = 1 : wellNum
        
        [wellData(:, i), ~, timeData(:, i)] = bsExtractWellDataByHorizon(...
            wellLogs{i}.wellLog, ...
            wellHorizonTimes(i), ...
            dataIndex, ...
            GInvParam.indexInWellData.time, ...
            GInvParam.upNum, ...
            GInvParam.downNum, ...
            filtCoef, ...
            GInvParam.dt);
        
    end
end